Comrv
westerndigitalcorporation/riscv-fw-infrastructure pull request #25
Opened 2020-02-16 16:28 UTC by rhwd

2020-02-17 12:17 UTC, oferShinaar commented on WD-Firmware/demo/build/utils.py
> +    exit(1)
you have bad "tabs" here.... just remove them

2020-02-17 12:18 UTC, oferShinaar requested changes
small tabs that need to be clear

2020-02-17 13:48 UTC, nati-rapaport approved these changes

2020-02-17 13:53 UTC, oferShinaar approved these changes

2020-02-18 10:27 UTC, nidalf approved these changes

2020-02-18 12:16 UTC, merged